### ISSUE TITLE
Request for turning this into an installable Python package

### ISSUE THREAD

**Issue by V0XNIHILI** [wtong98/mlp-icl#1]
First of all, thank you for your great paper! I really enjoyed reading it and it has lots of interesting results!

I am currently trying to build on top of your work, however, for this I would have to copy all of your task code into my repository. Therefore, I was wondering whether you could create a `pyproject.toml` file for this project so that I can add it as a dependency for my project.

I can also do this for you if you want.

**Comment by wtong98** [comment]
Thanks for reaching out! That's a fantastic idea. Feel free to open a PR with the proposed changes!

**Comment by V0XNIHILI** [comment]
Dear @wtong98, please check out my PR!

**Comment by wtong98** [comment]
Will do, thanks! Been absolutely swamped this semester, will check it out as soon as possible. Thanks for the contribution!
